name: flutter_alipay_alike_app
description: "Flutter Alipay-Alike App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # TDesign Components
  tdesign_flutter: ^0.1.8

  # Flutter Localizations
  intl: ^0.17.0

  # WindowManager
  window_manager: ^0.4.2
  # Scrollable Positioned List
  scrollable_positioned_list: ^0.3.8
  # Flutter Hooks
  flutter_hooks: ^0.20.5

  # Linq In Dart
  darq: ^2.0.0

  # Dio
  dio: ^5.8.0+1

  # Functional Widget
  functional_widget: ^0.10.2
  # Functional Widget Annotation
  functional_widget_annotation: ^0.10.0

  # Scroll To Refresh 下拉出现新页面
  pull_to_refresh_flutter3: ^2.0.2

  # Video Player
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.

  # Logger
  logging: ^1.3.0

  # Riverpod
  flutter_riverpod: ^2.5.1
  # Riverpod Annotation
  riverpod_annotation: ^2.3.5

  # Screen Adaptive Tool
  flutter_screenutil: ^5.9.3

  # Riverpod Hooks Support
  hooks_riverpod: ^2.6.1

  # Bluetooth
  flutter_blue_plus: ^1.34.5

  # Windows Bluetooth
  flutter_blue_plus_windows: ^1.26.1

  # GoRouter
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Riverpod Generator
  riverpod_generator: ^2.4.3
  # Build Runner
  build_runner: ^2.4.8
  # Lints Libs
  flutter_lints: ^4.0.0

  custom_lint: ^0.6.8

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/fc-regular.ttf
    - assets/images/swiper/swiper_bg1.png
    - assets/images/swiper/swiper_bg2.png
    - assets/images/swiper/swiper_bg3.png

  fonts:
    - family: FC
      fonts:
        - asset: assets/fonts/fc-regular.ttf

# build runner configuration
targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
            - lib/**.g.dart